apiVersion: v2
name: token-tumbler
description: A Helm chart for token-tumbler — a GitLab access token rotation worker.
type: application
version: 1.1.6
appVersion: "1.1.6"
home: https://github.com/nabsku/token-tumbler
sources:
  - https://github.com/nabsku/token-tumbler
maintainers:
  - name: nabsku
    url: https://github.com/nabsku
keywords:
  - gitlab
  - token
  - rotation
  - secrets
annotations:
  category: Developer Tools
