services:
  token-tumbler:
    image: ghcr.io/nabsku/token-tumbler:latest
    build: .
    volumes:
      - ./config.yaml:/config.yaml:ro
    environment:
      - GITLAB_TOKEN=${GITLAB_TOKEN:?Set GITLAB_TOKEN}
      - GITLAB_URL=${GITLAB_URL:?Set GITLAB_URL}
      - TOKEN_TUMBLER_INTERVAL=${TOKEN_TUMBLER_INTERVAL:-}
      - TOKEN_TUMBLER_METRICS_ADDR=${TOKEN_TUMBLER_METRICS_ADDR:-:9090}
      - APPROLE_ID=${APPROLE_ID:-}
      - APPROLE_SECRET=${APPROLE_SECRET:-}
      - VAULT_TOKEN=${VAULT_TOKEN:-}
      - VAULT_K8S_TOKEN_PATH=${VAULT_K8S_TOKEN_PATH:-}
    ports:
      - "9090:9090"
