{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "token-tumbler.fullname" . }}
  labels:
    {{- include "token-tumbler.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITLAB_TOKEN: {{ required "A valid .Values.env.gitlabToken or .Values.existingSecret is required!" .Values.env.gitlabToken | quote }}
  GITLAB_URL: {{ required "A valid .Values.env.gitlabUrl or .Values.existingSecret is required!" .Values.env.gitlabUrl | quote }}
  TOKEN_TUMBLER_INTERVAL: {{ .Values.env.tokenTumblerInterval | quote }}
  {{- if .Values.env.approleId }}
  APPROLE_ID: {{ .Values.env.approleId | quote }}
  {{- end }}
  {{- if .Values.env.approleSecret }}
  APPROLE_SECRET: {{ .Values.env.approleSecret | quote }}
  {{- end }}
  {{- if .Values.env.vaultToken }}
  VAULT_TOKEN: {{ .Values.env.vaultToken | quote }}
  {{- end }}
  {{- if .Values.env.vaultK8sTokenPath }}
  VAULT_K8S_TOKEN_PATH: {{ .Values.env.vaultK8sTokenPath | quote }}
  {{- end }}
{{- end }}
